### PR TITLE
New About feature

### PR DESCRIPTION
**Pull request by SchBenedikt**
I have added a new function so that you have the “Info” item first in the menu, from which two more items branch off, once to the list of all contributors and once to the version field. The version number is stored in the file. If this does not match the latest version number of the last release, it will indicate that a new update is available.
image

### CODE REVIEW

**Review by Telephos — APPROVED** [review]
Looks good! We may want to do something later with the "Help" button on the "about" dialog box. Currently it just changes the cursor as if it was disabled but you can still click off. You can't see it on a screengrab, but let me know if you get the same result. 

About

I mentioned the word count thing on PR#21.

**Comment by SchBenedikt** [comment]
Yes, I saw the one about the cursor, but I didn't know what else I could link...
But I thought it made a lot of sense.
Maybe we can link that to the release page.

**Comment by SchBenedikt** [comment]
If the counter works, I'll merge this too.

**Comment by SchBenedikt** [comment]
Have you seen already my installer software for the Text-Editor?
https://github.com/SchBenedikt/installer/blob/main/main.py

**Pull request merged**
